### ISSUE TITLE
[FEATURE] ClickGui more readable ui

### ISSUE THREAD

**Issue by kvdlxne** [CCBlueX/LiquidBounce#1015]
### Describe your feature request.

At the beginning, sorry for my english.

Just a new look for the ClickGui module that will be:
- More readable than panels with categories
- More customized
- Smaller (current gui doesn't fit on my screen)
- Will remove some modules, for example only ESP instead ItemESP, BlockESP, HoleESP etc.

I know the last point will be more complicated than it seems.
Also this feature is partly related to other earlier features, look [here](https://github.com/CCBlueX/LiquidBounce/issues/800), [here](https://github.com/CCBlueX/LiquidBounce/issues/706) and [here](https://github.com/CCBlueX/LiquidBounce/issues/677).

### Additional context

Prototype: ![new_ui](https://user-images.githubusercontent.com/65787223/233862937-3a7c5612-02c7-4aa8-bcf9-11ac59f3d471.png)

I did it in a few hours and I still don't fully understand how svelte works. Of course, this is an incomplete prototype, created just to visualize what I wrote earlier.

**Comment by Razzy52** [comment]
If you finish this you should be able to create a pull request and it may get merged?

**Comment by kvdlxne** [comment]
I need opinions, I don't want to continue this if it's a bad idea.

**Comment by CzechHek** [comment]
> I need opinions, I don't want to continue this if it's a bad idea.

Looks good so far, I wonder how you will deal with values.

**Comment by 1zun4secondary** [comment]
It might have been good to mention that you are working on a ClickGUI theme for nextgen. Not for legacy, that probably most of the people here thought. Anyway of course, go ahead. It won't be a likely that this will be added to our client, but now comes the point:

We will feature a theme system, which means you can override default elements like the ClickGUI with your theme.
https://github.com/CCBlueX/LiquidBounce/issues/255

If we are able to we will feature these themes on our website like we do with Scripts (but better than we currently do). Our script page will most likely turn into a whole market place for configs, scripts, themes and so on. Marketplace not really because we are not intending to allow people to sell there, but you get the idea.

From design perspective I would add a a border around the category buttons and add roundness to the whole clickgui and maybe button.

I would also recommend moving this to our Forum: https://forums.ccbluex.net/
GitHub Issues is not really intended for this :)

**Comment by 1zun4** [comment]
With v0.1.5 if you are still interested you can make this theme and put it into the "themes" folder and apply it using .client theme set name
