### ISSUE TITLE
[BUG] Killaura tries to sprint backwards

### ISSUE THREAD

**Issue by narutoDev** [CCBlueX/LiquidBounce#1170]
### LiquidBounce Build/Version

b80

### Operating System

macOS

### Minecraft Version

1.8.9

### Describe the bug

Killaura with silent strafe tries to sprint in the direction the player is looking at clientside, even when looking in the opposite direction serverside, effectively trying to sprint backwards.

### Steps to reproduce

Go on anticheat-test.com
Select Grim anticheat
Warp to killaura area
Use silent strafe and sprint in the opposite direction the player is looking serverside. 

### Client Log

```shell
-
```

**Comment by narutoDev** [comment]
The issue is more noticeable when the killaura fov is much higher than the real fov and keepsprint is enabled

**Comment by ghost** [comment]
Mind giving us a little bit more information? For example, the server you tried it on, the KillAura settings.

**Comment by narutoDev** [comment]
Grim and Matrix on anticheat-test.com
3.0 Range
3.5 Scan-Range
Any turn speed
FOV 180
With and without keepsprint enabled and while sprinting
Grim flags for Simulation and AimModulo360

**Comment by ghost** [comment]
That's how it is by design. It is not supposed to stop sprinting when the difference between your actual angle and the server side angle should make it do so. In other words, it's not an issue.

You can make the cheat stop running by enabling the Sprint module and toggle these options below:

Mode -> `Vanilla`
Disable `AllDirections`
Enable `CheckServerSide`
Disable `CheckServerSideOnlyGround`

By doing so the module will simulate real sprint stopping.

Note that Grim in that server you mentioned will also "detect" the client for simulation when you slow down, which is a false. Do not worry about it if that happens.

**Comment by narutoDev** [comment]
Thanks a lot for the detailed explanation and workaround.
