### ISSUE TITLE
[BUG] 2 KillAura bugs

### ISSUE THREAD

**Issue by gabrielvicenteYT** [CCBlueX/LiquidBounce#1205]
### LiquidBounce Build/Version

b82

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

KillAura Silent Strafe flags on Grim and AAC, and even when KeepSprint is off, though it reduces motion as expected, it does not stop giving sprint packets, even when the motion's reduced.

### Steps to reproduce

- Use KillAura with Silent Strafe, and turn KeepSprint off
- Go on AntiCheat-Test or Loyisa's Test Server
- Voilà!

### Client Log

```shell
Logs aren't needed, it doesn't give any errors, just code issues.
```

### Screenshots

https://streamable.com/8dyol0

**Comment by ghost** [comment]
You were being detected because you were using the wrong Sprint mode. The `Legit` mode only covers the actual player's rotation and disables any other option that violates vanilla logic. The strafe was designed to ignore if you sprint or not, I have explained it, [here](https://github.com/CCBlueX/LiquidBounce/issues/1170#issuecomment-1652785021) and [here](https://github.com/CCBlueX/LiquidBounce/issues/779#issuecomment-1660833357). The whole strafe code can be removed and instead implement a nextgen-like one easily, but it will ruin the functionality of other modules that require Sprint regardless if the rotation asks the cheat to stop sprinting or not.
