### ISSUE TITLE
[FEATURE] Update to mc 1.17 using FabricMC

### ISSUE THREAD

**Issue by 1zun4** [CCBlueX/LiquidBounce#167]
I'll update LiquidBounce to 1.16.3 instead of using a cross version system (https://github.com/CCBlueX/LiquidBounce-Issues/issues/3553).

**Comment by kawaiinekololi** [comment]
It's going to take a while until I've ported everything to the new version, also we'll have to add something like ViaFabric (protocol hack) so you're able to join 1.8-1.16 etc (+ add sword blocking back etc).
Probably many scripts are going to break, because of the minecraft version change.
But I think it's a really good choice. Like I've already said in my forum post (https://forums.ccbluex.net/topic/597/what-the-heck-we-re-doing): _It's a way easier and less messy approach, which means we can even use LWJGL 3 and other new stuff._

**Comment by MaxHD00** [comment]
UFF

**Comment by MaxHD00** [comment]
In theory a good idea. It's just that Liquidbounds is totally outdated. Everything is on old AAC 3 niveau. AAC4, Intave, Matrix etc. are not supported at all. Before there will be no updates for another 4 months, because the version will be changed again, it would be better to calculate the current version. Especially because we don't know if this 1.16 Fabric is not as stupid as the "crossversion". In the beginning we were told that this was a great idea. But the "crossversion" took much more effort. Fabric will probably have its problems too. It begins that it is no longer Forge. Let's hope that no problem appears.
Furthermore lb is on the 1.16. But everybody is playing for the 1.8.9. It is clear that a fabric viaversion will make sure that you can join the 1.8, but many features that were added with the versions have to be fixed. You will do that as well, but that also means that it will take even longer until bypasses updates for Liquidbounce will be released. The cross version already took 4 months. Porting Liquidbounce to 1.16.3, adapting it to 1.8 and adding 1.8 features will be very difficult and take a long time. I guess that there will be some bypasses in January. Whereby the scripts will not be compatible anymore. And the 1.16 code is very different from the 1.8. I have a dull feeling that no one will use lb and no one will want to do scripts anymore, because you don't want to get used to the 1.16 scripting language, because all other clients except Liquidbounce will run on the 1.8.

**Comment by ForyxCraft** [comment]
@MaxHD00 
1. ViaFabric will handle all the packet stuff.
2. Sigma is also on 1.16.X and many people use it.

**Comment by hahayesfun** [comment]
> 
> 
> @MaxHD00
> 
>     1. ViaFabric will handle most of the packet stuff.
> 
>     2. Sigma is also on 1.16.X and many people use it.

many don't specially use it because its 1.16 tho, cheating is most popular on 1.7.10, 1.8.9 and 1.12.2

**Comment by SenkJu** [comment]
> > 
> > 
> > @MaxHD00
> > 
> >     1. ViaFabric will handle most of the packet stuff.
> > 
> >     2. Sigma is also on 1.16.X and many people use it.
> 
> many don't specially use it because its 1.16 tho, cheating is most popular on 1.7.10, 1.8.9 and 1.12.2

You will be able to use LiquidBounce on any server from 1.8 to 1.16.

**Comment by MaxHD00** [comment]
> @MaxHD00
> 
> 1. ViaFabric will handle most of the packet stuff.
> 2. Sigma is also on 1.16.X and many people use it.

1: By far not everything is managed by Viafabric You can join 1.8 servers, but 1.8 blocking or 1.8 sneaking is not available to my knowledge. And as I know Marco, he thinks from 80% of all 1.8 features, that you don't have to add this, because the new one is better. e.g. F5 crossher is not available anymore from version 1.9 on.

2: Sigma has no scripts. And also not as many features as Liquidbounce. Sigma is also not a Forge. And Sigma is not totally outdated like Liquidbounce.

Translated with www.DeepL.com/Translator (free version)

**Comment by MaxHD00** [comment]
> > > @MaxHD00
> > > ```
> > > 1. ViaFabric will handle most of the packet stuff.
> > > 
> > > 2. Sigma is also on 1.16.X and many people use it.
> > > ```
> > 
> > 
> > many don't specially use it because its 1.16 tho, cheating is most popular on 1.7.10, 1.8.9 and 1.12.2
> 
> You will be able to use LiquidBounce on any server from 1.8 to 1.16.

We all know that. That's not what he meant either. He mentioned in general that you cheat the most in 1.7, 1.8 and 1.12. Especially in 1.8 it is.

**Comment by SenkJu** [comment]
We will take care of blocking. I don't see how scripts should be a problem or why we shouldn't update to the latest version.

**Comment by MaxHD00** [comment]
only have to consider that liquidbounce is currently outdated. You should go to 1.16 if you have AAC4, Intave and Matrix Bypasses in your client again. Most of the clients I know go to other clients because nothing works on some servers. 
e.g. On Intave the Killaura does not work. After about 15 minutes you will be banned. No matter what realistic settings you have.

**Comment by MaxHD00** [comment]
There is no AAC4/Intave or Matrix Scaffold or Speed. (or other bypasses)

**Comment by SenkJu** [comment]
What? The whole point of doing it this way is that we only have to develop a single version. We definitely won't make a 1.12 version first just to make another version for 1.16 once we have AAC bypasses. What kind of logic is that? Why not 1.16? Why 1.12? Just don't play on 1.16 servers if you don't need it.

**Comment by MaxHD00** [comment]
I'm not talking about that. Change if necessary not the version first. And do it later.
(When liquidbounce has bypasses again)

**Comment by SenkJu** [comment]
No. When we update to 1.16 our community will change. There aren't even any big servers who use Intave or AAC4. Why should we waste time on developing bypasses for those AntoCheats if only a fraction of our community would benefit from them?

**Comment by MaxHD00** [comment]
Fine.

**Comment by yorik100** [comment]
As long as many scripts are broken only for this version, it'll be good

**Comment by Litely1222** [comment]
5FPS.mp4

**Comment by E404NNF** [comment]
What I understand is we will get a 1.8.9 and 1.16.3 builds, is that right?

**Comment by NurMarvin** [comment]
> What I understand is we will get a 1.8.9 and 1.16.3 builds, is that right?

No. There will be one build for 1.16.3 (which will be kept up to date with the latest Minecraft version since it's very easy with Fabric unless there is a major change in Minecraft's code) and then we'll add the ability to connect to servers with older versions through a "proxy". Basically you will have one version that runs on the latest version of Minecraft which can connect to any Minecraft server version above a certain threshold, which will *probably* be 1.8 but I'm not sure about that.

**Comment by E404NNF** [comment]
Well, that has some cons and pros tbh but, I wish that happens! There will be modules for 1.9+ pvp/exploits, right?

**Comment by NurMarvin** [comment]
> Well, that has some cons and pros tbh but, I wish that happens! There will be modules for 1.9+ pvp/exploits, right?

We'll try to maximize the pros over the cons, so e.g. we will (probably) somewhat recreate the physics of each Minecraft version that will be supported by the client which will then prevent people from getting flagged that way.
Apart from that I'm not really aware of any other cons, but feel free to enlighten me what other cons there might be.
To answer your question regarding 1.9+ PVP/Exploit modules: If we are talking about Crystal Aura or other similar niche modules that only really have a use on one single server (type), the answer is maybe. I know we have added such modules in the past for e.g. Mineplex's Prophunt gamemode or Hypixel's Cops and Robbers, but that was prior to the introduction of scripts, so if it doesn't make the cut for being added directly to the client, someone might make a script for it.
Modules like EntitySpeed however will most likely be implemented since there's a general use case on a lot of different servers for it. I hope that cleared things up.

**Comment by E404NNF** [comment]
Aight thanks for clearing things up!

**Comment by E404NNF** [comment]
I still really hope we get atleast a 1.12.2 forge build with the fabric ones for people who can't run neweer versions in the future(which is I assume never as you told me.)

**Comment by yorik100** [comment]
> 
> 
> > What I understand is we will get a 1.8.9 and 1.16.3 builds, is that right?
> 
> No. There will be one build for 1.16.3 (which will be kept up to date with the latest Minecraft version since it's very easy with Fabric unless there is a major change in Minecraft's code) and then we'll add the ability to connect to servers with older versions through a "proxy". Basically you will have one version that runs on the latest version of Minecraft which can connect to any Minecraft server version above a certain threshold, which will _probably_ be 1.8 but I'm not sure about that.

Hold up, wait a minute, there will only be a 1.16.3 build for fabric, but the 1.8-1.12 forge build will still get supported, right? Marco stated that there would be a 1.16.3 fabric version OUT of the 1.8-1.12 forge

**Comment by E404NNF** [comment]
> Hold up, wait a minute, there will only be a 1.16.3 build for fabric, but the 1.8-1.12 forge build will still get supported, right? Marco stated that there would be a 1.16.3 fabric version OUT of the 1.8-1.12 forge

From what I understand, no

**Comment by yorik100** [comment]
> 
> 
> > Hold up, wait a minute, there will only be a 1.16.3 build for fabric, but the 1.8-1.12 forge build will still get supported, right? Marco stated that there would be a 1.16.3 fabric version OUT of the 1.8-1.12 forge
> 
> From what I understand, no

That doesn't make any sense

**Comment by MaxHD00** [comment]
Forge will not be supported in the new Liquidbounce version. But maybe it will be implemented. I hope so, because I also play 1.12.2 mods for example, and I would like to have Liquidbounce there.

**Comment by yorik100** [comment]
> 
> 
> Forge will not be supported in the new Liquidbounce version. But maybe it will be implemented. I hope so, because I also play 1.12.2 mods for example, and I would like to have Liquidbounce there.

- Literally every person using LiquidBounce

**Comment by TheBlocky** [comment]
can't wait for the moment that they realize preformance gonna die cause sodium is incompatible with LB's rendering engine

**Comment by Leejames2305** [comment]
@TheBlocky I think they also recoded the Render engine.

**Comment by TheBlocky** [comment]
> @TheBlocky I think they also recoded the Render engine.

ok so they have IQ

**Comment by kawaiinekololi** [comment]
> can't wait for the moment that they realize preformance gonna die cause sodium is incompatible with LB's rendering engine

Why should it be incompatible? We're always working with Sodium in mind.

**Comment by E404NNF** [comment]
Would there if any plans to support Optifine?

**Comment by kawaiinekololi** [comment]
> Would there be any plans to support Optifine?

Of course. OptiFine doesn't change that much, so it probably doesn't need any special treatment.

**Comment by E404NNF** [comment]
> > Would there be any plans to support Optifine?
> 
> Of course. OptiFine doesn't change that much, so it probably doesn't need any special treatment.

I've heard that Optifine changes the vanilla rendering code in recent version, it's not working with many mods correctly because of that change, and the x-ray of serveral hacked/utility clients aren't working because of it, so, probably it needs special treatment

**Comment by kawaiinekololi** [comment]
Might be, but we are aware of the importance of OptiFine (and/or Sodium) and going to make it compatible.

**Comment by yorik100** [comment]
> 
> 
> > > Would there be any plans to support Optifine?
> > 
> > 
> > Of course. OptiFine doesn't change that much, so it probably doesn't need any special treatment.
> 
> I've heard that Optifine changes the vanilla rendering code in recent version, it's not working with many mods correctly because of that change, and the x-ray of serveral hacked/utility clients aren't working because of it, so, probably it needs special treatment

I can confirm, x-ray doesn't work properly

**Comment by E404NNF** [comment]
decided to try LB 1.16.5, the game crashes when entering a world, a `[14:29:35] [main/FATAL]: Unreported exception thrown!` fatal error appears when entering a world and causes the game to crash, here's a log: https://pastebin.com/raw/h2ync5id
should i make an issue about this or just keep it here?

**Comment by kawaiinekololi** [comment]
> decided to try LB 1.16.5, the game crashes when entering a world, a `[14:29:35] [main/FATAL]: Unreported exception thrown!` fatal error appears when entering a world and causes the game to crash, here's a log: https://pastebin.com/raw/h2ync5id
> should i make an issue about this or just keep it here?

The nextgen version is not supposed to be used in a launcher yet.

**Comment by 1zun4secondary** [comment]
https://github.com/CCBlueX/LiquidBounce/tree/nextgen_1.17
