### ISSUE TITLE
[FEATURE] misc autopot improvements

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#1740]
### LiquidBounce Branch

Both

### Describe your feature request.

In autopot, when the module decides to throw potions, disable killaura before starting so that the player isn't doing two things at once. It consistently causes bans on most servers when playing potpvp, and disabling killaura then enabling autopot usually prevents that.
Some clientside slot picking similar to the options in the autoblock settings on scaffold would be nice. Smoother rotations and an option to not be silent rotations would be good as well.

**Comment by 1zun4** [comment]
Nextgen features pause combat time, which essentially does pauses any combat for the specified amount of time.
AutoSoup has this implemented, AutoPot can have this too, but both legacy and nextgen can't do both at the same time anyway since the rotations need to be updated first before it can throw anything or attack again.
