### ISSUE TITLE
[FEATURE] Freecam can't interact with entities or blocks through walls. 

### ISSUE THREAD

**Issue by Razzy52** [CCBlueX/LiquidBounce#1769]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Meteor has an example of how this works.  It allows you to interact with chests, npc's or place blocks through walls.

**Comment by 1zun4** [comment]
This was intended since LiquidBounce Freecam is supposed to bypass. The reason you can interact with entities or blocks in some clients is that they have a more poorly implemented Freecam which is easier detect for an anti-cheat. I understand this might be useful for some cases, but simply use GhostHand instead.
