### ISSUE TITLE
[BUG] Conditional options break when changing a mode value

### ISSUE THREAD

**Issue by superblaubeere27** [CCBlueX/LiquidBounce#1955]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

I mean what the hell is even that?

### Steps to reproduce

1. Change a mode that has it's own values
2. ???
3. Profit

### Client Log

```shell
-
```

### Screenshots

![image](https://github.com/CCBlueX/LiquidBounce/assets/22642852/8d78f674-50fe-4d5e-b27a-fd704d65c0fd)

**Comment by 1zun4** [comment]
It is a Svelte bug. Will be fixed with https://github.com/CCBlueX/LiquidBounce/pull/1442

**Comment by leumasme** [comment]
Code in Question: https://github.com/CCBlueX/LiquidBounce/blob/32ccda6b2b1808c6c42dfb851c2df0a29c4ab403/src-theme/src/routes/clickgui/clickgui/settings/ChoiceSetting.svelte#L47-L53

Probably fixable using a keyed each block: https://svelte.dev/examples/keyed-each-blocks

**Comment by 1zun4** [comment]
> Code in Question:
> 
> https://github.com/CCBlueX/LiquidBounce/blob/32ccda6b2b1808c6c42dfb851c2df0a29c4ab403/src-theme/src/routes/clickgui/clickgui/settings/ChoiceSetting.svelte#L47-L53
> 
> Probably fixable using a keyed each block: https://svelte.dev/examples/keyed-each-blocks

Thank you, but either I am doing something wrong or it does not work.
https://github.com/CCBlueX/LiquidBounce/commit/75b658ea4637dda61eab79ea5d6e49ad207342d8

**Comment by leumasme** [comment]
https://github.com/CCBlueX/LiquidBounce/assets/29953391/cc09ab26-8e20-4512-b020-d08c9047b5a7

Works fine with keyed each block in ChoiceSetting.svelte  
Note that the dev setup for the frontend currently does not work at all ever since #1557 (because the code uses the current URL as the websocket URL, which results in the wrong port when using the dev server), so you might have not actually been viewing your modified UI when testing.

**Comment by 1zun4** [comment]
Fixed with the new theme.
