### ISSUE TITLE
[BUG] Optimization issues

### ISSUE THREAD

**Issue by Gongillioning** [CCBlueX/LiquidBounce#2071]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.5 30e3781 nightly

### Operating System

Windows 10

### Minecraft Version

1.20.4

### Describe the bug

When i have the HUD on, or any heavy render module like KillAura or both Nametags and StorageESP, my game lags A LOT, i don't have a bad PC either, it can handle 32 chunks and fancy graphics (and most graphic options at high) at 55-60 fps, i also just get general lag and freezes when using Nextgen

### Steps to reproduce

-Open LiquidBounce Nextgen
-Go to any world
-Activate HUD or Nametags (Atleast on Mobs)

### Client Log

```shell
N/A
```

**Comment by 1zun4** [comment]
I will close this issue since even my AMD Ryzen 7 5700U iGPU can handle the GUI with 150fps+ and zero delay, as well as a new Theme Implementation was pushed (which might have fixes this issue). If this issue persists try creating a new issue, but honestly there is not much to change to the fact that Minecraft and JCEF requires performance and if you are running a potato or bad drivers, there is nothing we can do.
