### ISSUE TITLE
[BUG] Broken Scripts

### ISSUE THREAD

**Issue by hahayesfun** [CCBlueX/LiquidBounce#227]
**Describe the bug**
Some scripts are broken in versions after cross version merge which is pretty frustrating sometimes because scripts latest bypasses or better features overall sometimes and without them LB is worse. Core scripts and some render scripts (such as Target HUD by Chochopie) are broken (There are probably more broken scripts that I don't know about probably) so I think it would be a really good idea to at fix scripts 

**Screenshots**

https://prnt.sc/un8v3v

**Additional information:**
 - OS: [Windows]
 - LiquidBounce Build Version [b73 (Latest)]
 - Minecraft Version [1.8.9]

**Comment by kawaiinekololi** [comment]
waiting for https://github.com/CCBlueX/LiquidBounce/issues/167

**Comment by yorik100** [comment]
> **WE CAN'T SUPPORT EVERY SCRIPT FOREVER**!
> Also we're waiting for #167

So it'll be like Minecraft stuck on 1.8.9 except LiquidBounce will be stuck on b72, amazing

**Comment by kawaiinekololi** [comment]
> > **WE CAN'T SUPPORT EVERY SCRIPT FOREVER**!
> 
> So it'll be like Minecraft stuck on 1.8.9 but with LiquidBounce
> 
> 

You can't compare something like that with LiquidBounce. The ScriptAPI is a optional feature, which is community based. We provide a **safe** api which allows every developer to make scripts without worrying about future versions.
There are a lot of developers which are using "hacky" solutions or use classes from lb. A good example is the font renderer, which recieved many changes, but is used by some scripts without a **safe** api (directly using our classes)
NOW. TELL ME. HOW WE CAN KEEP UPDATING OUR CLIENT WHEN SOMEONE LIKE YOU IS CRYING JUST BECAUSE ONE OR TWO SCRIPTS DOESN'T WORK ANYMORE BECAUSE THEIR USING THE LIQUIDBOUNCE FEATURES DIRECTLY.
We're open for requests to add new features to our **safe** ScriptAPI.
It seems you have no idea, that we provide support for every script forever.

**Comment by yorik100** [comment]
> 
> 
> > > **WE CAN'T SUPPORT EVERY SCRIPT FOREVER**!
> > 
> > 
> > So it'll be like Minecraft stuck on 1.8.9 but with LiquidBounce
> 
> You can't compare something like that with LiquidBounce. The ScriptAPI is a optional feature, which is community based. We provide a **safe** api which allows every developer to make scripts without worrying about future versions.
> There are a lot of developers which are using "hacky" solutions or use classes from lb. A good example is the font renderer, which recieved many changes, but is used by some scripts without a **safe** api (directly using our classes)
> NOW. TELL ME. HOW CAN WE KEEP UPDATING OUR CLIENT WHEN SOMEONE LIKE YOU IS CRYING JUST BECAUSE ONE OR TWO SCRIPTS DOESN'T WORK ANYMORE BECAUSE THEIR USING THE LIQUIDBOUNCE FEATURES DIRECTLY.
> We're open for requests to add new features to our **safe** api.
> It seems you have no idea, that we're not able to provide support for every script forever.

The examples you gave are easy to fix, but when everything gets changed like for ScriptAPI v2 then it just kills 90% of the scripts and it'll take me hours to update 30 scripts

**Comment by derech1e** [comment]
> > > > **WE CAN'T SUPPORT EVERY SCRIPT FOREVER**!
> > > 
> > > 
> > > So it'll be like Minecraft stuck on 1.8.9 but with LiquidBounce
> > 
> > 
> > You can't compare something like that with LiquidBounce. The ScriptAPI is a optional feature, which is community based. We provide a **safe** api which allows every developer to make scripts without worrying about future versions.
> > There are a lot of developers which are using "hacky" solutions or use classes from lb. A good example is the font renderer, which recieved many changes, but is used by some scripts without a **safe** api (directly using our classes)
> > NOW. TELL ME. HOW CAN WE KEEP UPDATING OUR CLIENT WHEN SOMEONE LIKE YOU IS CRYING JUST BECAUSE ONE OR TWO SCRIPTS DOESN'T WORK ANYMORE BECAUSE THEIR USING THE LIQUIDBOUNCE FEATURES DIRECTLY.
> > We're open for requests to add new features to our **safe** api.
> > It seems you have no idea, that we're not able to provide support for every script forever.
> 
> The examples you gave are easy to fix, but when everything gets changed like for ScriptAPI v2 then it just kills 90% of the scripts and it'll take me hours to update 30 scripts

When it is so easy to fix, why then you dont fix it? So dont cry anymore and fix it yourself. Create a Pull Request and everything is fine. 
**"It's that simple"**

**Comment by yorik100** [comment]
> 
> 
> > > > > **WE CAN'T SUPPORT EVERY SCRIPT FOREVER**!
> > > > 
> > > > 
> > > > So it'll be like Minecraft stuck on 1.8.9 but with LiquidBounce
> > > 
> > > 
> > > You can't compare something like that with LiquidBounce. The ScriptAPI is a optional feature, which is community based. We provide a **safe** api which allows every developer to make scripts without worrying about future versions.
> > > There are a lot of developers which are using "hacky" solutions or use classes from lb. A good example is the font renderer, which recieved many changes, but is used by some scripts without a **safe** api (directly using our classes)
> > > NOW. TELL ME. HOW CAN WE KEEP UPDATING OUR CLIENT WHEN SOMEONE LIKE YOU IS CRYING JUST BECAUSE ONE OR TWO SCRIPTS DOESN'T WORK ANYMORE BECAUSE THEIR USING THE LIQUIDBOUNCE FEATURES DIRECTLY.
> > > We're open for requests to add new features to our **safe** api.
> > > It seems you have no idea, that we're not able to provide support for every script forever.
> > 
> > 
> > The examples you gave are easy to fix, but when everything gets changed like for ScriptAPI v2 then it just kills 90% of the scripts and it'll take me hours to update 30 scripts
> 
> When it is so easy to fix, why then you dont fix it? So dont cry anymore and fix it yourself. Create a Pull Request and everything is fine.
> **"It's that simple"**

Nothing is broken?

**Comment by kawaiinekololi** [comment]
It has nothing to do with ScriptAPI v2, we're still supporting legacy scripts. What are you talking about?

**Comment by Teals53** [comment]
bruh

**Comment by yorik100** [comment]
> 
> 
> It has nothing to do with ScriptAPI v2, we're still supporting legacy scripts. What are you talking about?

I know that it's not about ScriptAPI v2

**Comment by ponei** [comment]
Scripts broke because the new backend changed a lot of variables. They are mostly easy to fix, but require a bit of investigation by the developer of the script.
Example 1: Fonts changed to [IFontRenderer](https://github.com/CCBlueX/LiquidBounce/blob/master/shared/main/java/net/ccbluex/liquidbounce/api/minecraft/client/gui/IFontRenderer.kt) and the old "_FONT_HEIGHT_" variable changed to "_fontHeight_".
Example 2: Events on scripts return new backend variables that don't have all the old functions. "_module.on("attack")_" now returns [EntityImpl](https://github.com/CCBlueX/LiquidBounce/blob/master/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/injection/backend/EntityImpl.kt) instead of a regular EntityLivingBase. EntityImpl doesn't have a way to return health of the entity; "getHealth()" or a "health" variable doesn't exist, therefore breaking regular logic.

**Comment by kawaiinekololi** [comment]
https://github.com/CCBlueX/LiquidBounce/issues/317
