### ISSUE TITLE
[FEATURE] Question regarding Svaffold

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2565]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Can somebody please explain me the functionality of the 'Always' subsettings of the 'AutoBlock' settings and the 'ResetThreshold' settings of the Scaffold module?

**Comment by 1zun4** [comment]
AutoBlock automatically changes your slot to another block.
Always in this case will keep it at this slot until you turn off the module.

Reset is part of the rotation settings and simply means that when your crosshair is close to this threshold, it will snap back immediately. Can be removed I think and combined with Turn Speed, since it pretty much does the same... :thinking:
