### ISSUE TITLE
[FEATURE] Remove using chromium for gui

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#2711]
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Its so bloated, and it runs background processes on my PC.

**Comment by 1zun4** [comment]
then dont use hud and dont use clickgui and disable client apperance, who needs GUIs anyway, have fun

**Comment by ghost** [comment]
> then dont use hud and dont use clickgui and disable client apperance, who needs GUIs anyway, have fun

it always runs in the background, no way to disalbe, just use meteor client gui, looks as good and doesn't require extreme chrome bloat. On another note disable the slow ahhh animations for menus

**Comment by 1zun4** [comment]
Then use Meteor.

**Comment by superblaubeere27** [comment]
@1zun4 there is a problem though with chrome daemon processes which continue to run after the client terminates. Each of those processes for whatever reason takes 100% of one of the CPU's cores which is annoying.

**Comment by 1zun4** [comment]
> @1zun4 there is a problem though with chrome daemon processes which continue to run after the client terminates. Each of those processes for whatever reason takes 100% of one of the CPU's cores which is annoying.

Yes this is a bug when not closing the client properly (force exiting). But that's not a reason to entirely remove Chromium and throw away all of our work just because @ThrowerWay is crying because it's bloated.

As an alternative, we can provide Ultralight as a fallback, but due to the fact the Webkit in v1.3 is too outdated to understand our Theme properly, this cannot be done until v1.4 comes out (or at least bindings).
