### ISSUE TITLE
[FEATURE] Smart Telly Rotations

### ISSUE THREAD

**Issue by Coccocoahelper** [CCBlueX/LiquidBounce#2979]
### LiquidBounce Branch

Both

### Describe your feature request.

As of now, LiquidBounce (both legacy *and* next-gen)'s Scaffold telly rotations do not appear to be legit, neither to players nor to advanced anti-cheats. This is because they are based on normal Scaffold rotations, which are flawed and hunted for by anti-cheat developers. Instead, the rotations should emulate a normal Speed Telly player.

Advantages of legit player emulating:
1: Less anti-cheat detections. Since anti-cheat developers strive to patch hacked clients but not ban legit players, they probably tested their anti-cheat against Speed Telly players; this should be used for our advantage.
2: Faster block placing. I have tested Scaffolds in speed tests, and have found that Speed Telly players are significantly faster.

### Additional context

Below are some videos that I'd find helpful:

- Former Speed Tellying world record: https://youtube.com/watch?v=TaiZ70ZRKvQ

- Tap Speed Tellying tutorial: https://youtube.com/watch?v=Yw0r21LFmrg

**Comment by ghost** [comment]
not possible, this can't be improved any further. It's not 100% close to legit player but that doesn't mean that no legit will do the same. With good enough config it is really hard for anticheats to flag you. Also legit and the math use for rotation is pretty much aim at the same point. Also a lot of anticheats still 90% going to false if you really as fast as in the video since well maybe he is too good, and that literally a world record?

**Comment by EclipsesDev** [comment]
I agree with @Fyxar, its just not possible
