### ISSUE TITLE
[NEXTGEN] I don't think one of the goals is good

### ISSUE THREAD

**Issue by TheBlocky** [CCBlueX/LiquidBounce#314]
I think Scyter is not a good goal as it would completely kill preformance, so i think it should wait

**Comment by NurMarvin** [comment]
Sciter is actually pretty good for performance. We already conducted tests before adding it to the roadmap and didn't notice any large performance issues. Also, please don't open new issues regarding this, since you can just comment on the original issue available at #226. This makes it easier for us to organize things instead of having to keep track of 10 issues that all focus around the same thing.
