### ISSUE TITLE
[FEATURE] Localization

### ISSUE THREAD

**Issue by GoldenDog1218** [CCBlueX/LiquidBounce#338]
In my country a lot of people know English ,but they think this mod is hard to know what options are doing so I try to translation mod into our language but in 1.12.2 those text is not from *.lang file so can you tell how to translation the word in new version
 

plz :D

**Comment by mems01** [comment]
There is almost nothing to translate. If you think you don't understand those options, I guess you should improve your english instead.

**Comment by Really-why-not22** [comment]
> In my country a lot of people know English ,but they think this mod is hard to know what options are doing so I try to translation mod into our language but in 1.12.2 those text is not from *.lang file so can you tell how to translation the word in new version
> 
> plz :D

This is old information I found it on forum but I think it will help .
Hi. First off, I would like to thank xTony, BarbieHunter, Scropion3013, Marco, and SenkJu for all this information. xTony for being my friend. BarbieHunter for telling my stuff about configs. Scorpion3013 for telling me how to use the scriptAPI. Marco and SenkJu for creating liquidbounce (probably others as well).

Also, the 1.12.2 version of Liquidbounce isn't supported yet. It's very out-of-date and will probably no longer get any updates.

To add to the FAQ:
-Useful Scripting Api shenanigans.
-Every command in LiquidBounce and what they do.
-Every module in LiquidBounce and what they do.

Q: I can't download LiquidBounce. It says ADBLOCK DETECTED
A: First off, check this out, if that doesn't help, check this video by Scorpion3013 (might be outdated, please give me a new link if it is, Scorpion.) Also, disable your vpn and css changing addons like "dark reader" (thanks scorpion again)

Q: How do I install LiquidBounce?
A: Check this out. I hope it works for you. If not, I'll try to help you.

Q: How can I use different hacks or open the clickgui?
A: Press Right Shift on your keyboard to open the clickgui. If that doesn't open it up, type in chat .bind clickgui rshift and then press RightShift. To use a hack, simply click on the hack you want to activate. Right click on a hack in the clickgui to see its options.

Q: How can I bind different hacks to different keys?
A: Do .bind (hack name) (key). For example, .bind killaura r, .bind freeze insert, .bind longjump lbracket (will bind to [). To remove a bind, do .bind (hack name) none. .bind killaura none, .bind freeze none etc.

Q: How can I bypass or use autosettings and configs for certain servers?
A: Do .config load (server or anticheat). For example, .config load hypixel, or .config load ncp

Q: How can I get free alts?
A: The Bread Bakery is down unfortunately. It is now recommended to use https://thealtening.com as it is safe, secure, and updates quite often. Don't use FreeAlts.pw as it IS dangerous.

Q: Where's X hack?
A:

NoKnockBack/AntiVelocity/AntiKnockBack is called Velocity. It's at the bottom of the Combat section.
BHop/yPort/Speed is called Speed, yes, all of them. It's near the bottom of the Movement section. Just chose your setting for the server's anticheat.
KillAura/MultiAura/SwitchAura/LegitAura is called KillAura. Go in the setting and chose under "TargetMode" the "Multi" setting for MultiAura (WARNING!!! WON'T BYPASS ON MOST SERVERS!!!) Disable "SilentRotation" for LegitAura. For SwitchAura, chose under "TargetMode" the "Switch" setting. Chose range, ClickPerSecond (cps), etc in the settings.
TeleportAura is just TeleportHit.
Q: The ClickGui is too big!!!
A: Do .clickgui scale <0-1>. 1 is default, and 0.5 is half the size.

Q: My Killaura/Aimbot won't hit anybody.
A: Enable "Dead" under targets. Enable "Players" under targets. Enable "NoFriend" under "Combat". Disable Teams under "Misc". Change around the settings in AntiBot (1st thing under Misc). Enable and disable "AAC" and the "RayCast" settings until it works. If that didn't help, then idk what will. xD

Q: What does X module do?
A: I'll be explaining the modules that most ppl ask about.
Under Misc:
AntiBot: Makes KillAura and Aimbot not target Bots.
AtAllProvider: Let's say that there is George, Notch, and Cat on the server, and lets say you do the command /say @a. It will do the command /say and replace the @a with the name of each person, so it would do /say George then /say Notch then /say Cat.
ComponentOnHover: When hovering over some text, if the text has an action, it'll tell you what that action is.
LiquidChat: Be able to chat with other LiquidBounce users via .lc (message)
MidClick: Adds a friend when right clicking someone.
NameProtect: Replaces your name and/or skin of you and/or everyone client side.
NoRotationSet: Doesn't send rotation packets to the server I believe.
Spammer: Spams the chat with given text.
Teams: Prevents KillAura and Aimbot from attack team members.
---Thanks to Soulplexis for this.
Combat
Aimbot - aims at targets
Range: Range aimbot will aim at targets
TurnSpeed: How fast Aimbot turns your view
FOV: Target needs to be within this FOV to be aimbotted
OnClick: Aims only when mouse down.
Jitter: Shakes view to appear more legitimate
AutoArmor - Equips armor for you
MaxDelay, Mindelay: maximum and minimum delays between equipping armor
InvOpen: Equip armor only when inventory opened by you
SimulateInventory: Tells the server you opened your inventory when AutoArmor is equipping armor
NoMove: Prevents autoarmor from working if you don't move
ItemDelay: Item must be in your inventory for this amount of time before equipping
Hotbar: Equips armor in Hotbar (Ignores other options)
AutoBow - Shoots bow when fully pulled back automatically
AutoClicker - clicks for you
MaxCPS MinCPS: Minimum/maximum clicks per second.
Right: Auto-right click.
Left: Auto Left click
Jitter: Shakes view slightly when AutoClicker in action.
AutoLeave - Uses exploits to kick you when your health is low, for pvp logging
Health: Health at which it will kick you.
Modes
Quit - Quit packet
InvalidPacket - invalid position packet sent, kicks you
SelfHurt - tries to hit yourself
IllegalChat - Sends illegal character in chat to get you kicked such as Â§
AutoPot - Throws healing potions when your health is low.
Health: The minimum health value that the client will attempt to bring you to.
Delay: Delay between throwing potions
OpenInv: Refills potions in your hotbar only when inventory open
NoAir: Disables potion throwing if you are in the air
Modes
Normal - Aims down, throws
Jump - Jumps, throws pot up
Port - Throws pot up, jumps and ports down
AutoSoup - Uses mushroom soups when health is low, see AutoPot for it's functions.
AutoWeapon - Selects the best weapon to use when you attack an enemy
SpoofItem: Spoofs the item so you don't actually switch your hand-held item, but you deal the damage of the better weapon.
BowAimbot - Aims at targets when using a bow
Silent: Silent aim, your view doesn't change.
Predict: Attempts to predict target movements PredictSize is the amount ahead of the movement the aim is
Priority: Which targets will be aimed at first (Direction = closest to crosshair)
Mark: Marks the target aimed at
Criticals - Makes all or some of your hits critical hits (more damage)
Modes
Packet - Sends packets for critical hits (Insanely small jump)
HypixelPacket - Packet, but bypassed Hypixel (patched)
Noground - Basically tells the server you're in the air falling when you're on the ground so you get criticals
Hop - A small jump when you hit an enemy, causes critical hits, bypassed Mineplex/NCP long ago.
TPHop - Even smaller jump, for anticheats that detect packets but not small jumps.
Jump - Jumps like normal. Undetectable
LowJump - Jumps slightly lower than normal (Spartan bypass)
FastBow - Shoots the bow faster when you right click
Packets, 20 = fully charged arrows 15 = only about 75% charged arrows
Hitbox Increases hitboxes of targets by the amount of the slider.
Ignite - Uses flint and steel to set fire to nearby targets
KillAura - Attacks targets in range
MaxCPS, MinCPS: attacks per second variables.
HurtTime: Waits for targets to stop turning red (10 = doesn't wait 5 = waits halfway 0 = waits fully)
Range: Range in which targets will be attacked.
ThroughWallsRange: Range in which targets through walls will be attacked. 0 = don't attack through walls
RangeSprintReducement: Reduces range by this much when you are sprinting (4.8 range for example, is reduced to 4.5 when you are sprinting)
Priority: Health - Lowest health attacked first, Distance - Closest target attacked first, Direction - Closest to crosshair attacked first, LivingTime - Oldest target attacked first
TargetMode: Single - Locks onto one target, Switch - Switches to next priority target after hitting the first one, Multi - Hits multiple targets at once.
Multimode Ncp: Attacks entities close to the one you are attacking at the same time, used to work on NoCheatPlus (Long patched)
Multimode vanilla: for use in single player or no anticheat
Swing: will swing your hand or what your holding
KeepSprint: you will Keep Sprinting after hitting opponent
ThroughWalls: self explanatory
Autoblock: your sword will hit and block at the same time
InteractAutoblock: the Autoblock will interact with the entity
Blockrate: the % it will block
AAC: Makes KillAura bypass Advanced AntiCheats by hitting entities which appear inside of your opponent
Raycast: Hits any entity (Which is targeted) that is between you and your target (As if you aimed there and clicked)
RayCastIgnored: like raycast, but disregards Targets and hits anything between you and your target.
LivingRayCast: ignores all non living entities
Predict: predicts where the target is moving and aims ahead of them
PredictSize: how much it will aim forward of the target's movement
Failrate: the % the killaura fails to hit someone
LimitedMultiTargets: Multi-Mode will only be allowed to attack this many targets at once, 0 = infinite
Noinvattack: the killaura will not attack if you have your inventory open
NoinvattackDelay: how long it takes for the killaura to stop attacking when you have your inventory open
MinTurnSpeed: the minimum speed your head rotates
MaxTurnSpeed: the maximum speed your head rotates
FakeSwing: Swings your arm before hitting the target, for bypassing heuristic checks
SilentRotation: your head will only rotate on the server side.
RandomCenter: your aim will jitter slightly to appear more legitimate to anticheats mostly
Outborder: modifies RandomCenter to aim at the borders of the target's hitbox (?)
FOV: Field of view that the aura can hit.
Mark: will show the square to the entity you are attacking - Purely visual.
FakeSharp: shows fake sharpness enchantment particles - Purely visual.
NoFriends - Allows you to hit friends (.friend)
SuperKnockback - Increases knockback of opponents by abusing sprint mechanics
TNTBlock - Uses sword and blocks when TNT explodes
Fuse: The fuse of the TNT when you'll block with sword
AutoSword: Picks a sword to block with automatically
TeleportHit - When falling, if you click on any target (distance irrelevant) you will teleport to it, hit it, and teleport back (serversided)
Trigger - Hits targets when they're on your crosshair (See Autoclicker for similar options)
Velocity - Reduces or changes your knockback
Horizontal, Vertical: Amount of knockback taken in each direction for Simple mode
Modes
Simple - Sets knockback to above values
AAC - Reduces knockback bypassing AAC v3
AACPush - Pushes you slightly when hit instead of reducing, bypassing AAC v3
AACZero - Abuses AAC to glitch you to where you are when taking knockback
Jump - Jumps when knockback taken, (Basically only vertical)
Reverse - You can reverse the knockback taken and move in the attacker's direction
Reverse2 - Same as reverse, different method
Glitch - Attempts to exploit anticheats to set you back to where you are so you don't take knockback
ReverseStrength: Your ability to reverse the knockback of reverse mode
Reverse2Strength: ^
AACPushXZReducer: Amount your horizontal knockback for AACPush is reduced.
AACPushYReducer: Reduces vertical knockback of AACPush mode.
Airjump - This will allow you to jump when you're in the air (fly)
AirLadder - This allows you to climb ladders even when you arent pushing against the ladder block
AntiAFK - Patrols back and forth automatically to make you appear not AFK
AntiBot - Eliminates anticheat bots from being targeted if it fails the following checks..
Tab - Checks if player is in the tablist, if not is marked as bot
TabMode (Contains = contains the entity's tag Equals = the tag is the same as the name of the entity)
EntityID - Checks if the player has a broken entity ID (AAC1.9.10)
Color - Checks the color of the entity's team
LivingTime - Checks how long the entity has been existing for (Has to exist for a bit before it will be attacked
Ground - The entity must touch the ground at least once to be targeted
Air - If the entity is in the air for a long time it won't be attacked
InvalidGround - (A guess) Checks if the entity claims to be onground mid air
Swing - The entity must swing it's arm at least once to be targeted
Health - The entity must have a normal amount of health to be targeted
Derp - If the entity's head rotates at an impossible pitch, it won't be targeted (Headless derp)
WasInvisible - Similar to livingtime, but only after the entity is visible for a while it will be targeted.
Armor - Checks if entity has armor, if not won't target
Ping - Checks if the entity has a normal/any ping, otherwise it won't target
NeedHit - The entity needs to be hurt/display damaged animation at least once to be targeted (AAC addition pro)
AntiCactus - Prevents cactus damage by preventing you from touching cactus
AntiHunger - Sends less update packets to prevent you from becoming hungry
AutoBreak - Breaks any block you are looking at automatically
AutoFish - Cast a fishing rod, you will reel in fish when they appear automatically
AutoRespawn - When you die, you will respawn automatically (Or instantly)
AutoTool - Selects the best tool to use when you click on any block
AutoWalk - Walks forward automatically
BedGodmode - For 1.9, it allowed you to be invisible and hit people if you slept in a bed
Blink - Best way to explain blink is to tell how to use it. You are hiding behind a tree, there's a player looking around for you. Turn on blink, and walk behind another tree. You appear to teleport between trees, where as the server believes you just walked there but you were lagging.
Pulse: Blink will teleport you to where you are every PulseDelay (milliseconds)
BlockWalk - You will be able to walk on top of blocks such as cobwebs
BufferSpeed - You will be given a speed boost on different surfaces (To bypass AAC and Firefly, some other anticheats)
SpeedLimit - LImits the speed to the set MaxSpeed value
Buffer - You take a second to speed up
Stairs - Faster on Stairs
Stairsmode - new/old for different versions of AAC
Slabs - You go faster walking on slabs
Ice - Speed boost when on Ice
Snow - Speed boost when walking on Snow layers
SnowPort - You yport on Snow instead of just speed
Wall - Speed boost when against a wall
HeadBlock - Speed boost when block above your head
Slime - Speed when on Slime blocks
AirStrafe - You can turn mid-air (Strafe module)
NoHurt - Doesn't speed if you get hurt(?)
BugUp - Abuses anticheats to flag you back to where you fell off of if you fall
Modes
TeleportBack - Teleports you back
FlyFlag - Flags fly on anticheats (Nocheatplus)
OnGroundSpoof - Spoofs onground like Nofall to flag you up (damages i believe)
ChestAura - Opens any chest within range
Range - Range within which chests will be opened
Delay - How long until opening the next chest, good for cheststealer delays
Throughwalls - Opens chests through walls
VisualSwing - Swings arm (visual only, doesn't reallly matter)
Chest - Basically, you can change what block is considered a Chest
ChestStealer - Steals all items out of any chest you have opened
Max/mindelay - Delay between taking items
TakeRandomized - Steals items in a random order
OnlyItems - Doesn't take blocks I believe
NoCompass - Doesn't steal items out of compass guis(?) Doesn't take compasses?
AutoClose - Closes the chest when it's empty
AutoCloseMin/MaxDelay - Delay before closing the chest
CloseOnFull - Closes chest when your inventory is full
ChestTitle - Chest has to be named "Chest" to be stolen from. Multi-language support doesn't work for some..
CivBreak - Breaks blocks as fast as possible!
AirReset - Resets block breaking if you're in the air
RangeReset - Resets the block breaking if you go out of range of the block
ConsoleSpammer - This won't work most places, but spams admins/server console with errors so they can't see what you're doing.
Modes
Payload - Normal.. won't bypass pretty much anywhere
Minesecure - For minesecure anticheat
Delay - Delay between packet sending
Damage - Damages you (To bypass some anticheats, other things)
Modes
NCP - Fake fall damage (Doesn't actually work on NoCheatPlus)
AAC - Flings you in the air, I assume it's meant to use fall damage too
Damage - How many half-hearts worth of damage NCP mode does to you
Derp - Your head will be going nuts to other players
Headless - Your head goes at an invalid pitch so you appear headless
Spin - Your head spins around in a circle
Increment - How fast you spin using spin mode
If both are off, you will just spaz out randomly.
Eagle - Sneaks on the edge of blocks to fastbridge
FarmKingBot - For some minigame called FarmKing
FastBreak - Makes you break blocks faster than normal
BreakDamage - At this % of progress in breaking the block, the block will just break instantly. Example im 80% done mining cobblestone, it would just break instantly then. (0.80)
FastClimb - Climb ladders/vines faster
Modes
Normal - Normal mode.. Worked on very old nocheatplus, just normal.
OAAC - Old AAC bypassing. (1.9.10)
AACv3 - Bypassed an older version of aac v3, such as 3.0.5 or something
LAAC - Bypasses Latest aac versions
FastPlace - Place blocks faster (hold right click)
Speed - Higher value = slower place speed
FastStairs Go up stairs faster
LongJump - Uses LongJumps to go up stairs faster
FastUse - Consume potions/food faster
Modes
Instant - No anticheat mode, instantly eats
NCP - Nocheatplus, pretty fast.
AAC - AAC 1.9.10 mode, sometimes works on aac v3
Fly - Lets you fly where you otherwise couldn't
Modes
Vanilla - For vanilla (No anticheat), just a fast hard fly
SmoothVanilla - Like creative mode
NCP - Old nocheatplus bypass, doesn't work anymore (Damages you)
OldNCP - Even older nocheatplus bypass, doesn't work anymore
AAC - For AAC v 1.9.10 (you must fall for it to work)
AACv3 - For AAC v 3.0.5 I believe.
FastAACv3 - For aacv3 again, obviously doesn't work anymore.
AAC3.3.12 - You must fall into the void and you will be shot upward. Press Left control to slow down time so you can place water/web (fall damage)
AAC3.3.12-Glide - Self explanatory, not very good though..
AAC3.3.13 - Bypassed AAC 3.3.13, flings you high into the air
Gomme - For GommeHD server, you had to fall into the void for it to start bypassing, but it's patched.
Flag - Flags you very badly on anticheats.. not recommended!
CubeCraft - For Cubecraft, it may ban you so be careful using it
InfinityCubeCraft - Cubecraft server fly, patched.
InfinityVCubecraft - ^
Hypixel - Old Hypixel server fly, patched
OtherHypixel - Old Hypixel server fly, patched as well
LatestHypixel - Newer hypixel fly that somewhat works (Don't use the boost option)
BoostHypixel - Damages you and flies faster, bypasses Hypixel server
FreeHypixel - Freezes you, then you can fly using vanilla-type fly on Hypixel server (Patched!!)
Rewinside - An Airwalk fly for Rewinside server
TeleportRewinside - Teleportation fly for Rewinside server
Mineplex - An old fly made for Mineplex around 2018, patched
KeepAlive - Vanilla fly which spams keepalive packets, works on WatchCat anticheat
MineSecure - For Minesecure anticheat, horizontal speed depends on vanillaspeed
Spartan - Spartan anticheat fly, patched
Spartan2 - Spartan fly again, patched
BugSpartan - Damages you and flies using vanillaspeed (Patched)
KillSwitch - For KillSwitch anticheat, which doesn't exist anymore
HawkEye - for HawkEye anticheat, patched and hawkeye isn't used anymore anyway.
MineSucht - For Minesucht server, i believe this is patched?
Jetpack - Flies as if you have a jetpack, mostly for fun
HAC - For HeitTeir's anticheat, still bypasses
WatchCat - For watchcat anticheat
NeruxVace - For Neruxvace server, may be patched..
VanillaSpeed - Speed of Vanilla mode fly
VanillaKickBypass - Tries to bypass "Flying is not enabled" kick
MineplexSpeed - Self explanatory..
NCPMotion - NCP mode glides down at this motion (0.0 = no glide)
AACSpeed - AAC mode's speed horizontally
AAC3.3.12Motion - Motion upward of AAC 3.3.12
AAC3.3.13Motion - Motion Upward of AAC 3.3.13 mode
NeruxVace-Ticks - For Neruxvace mode, the tick interval for when it glides/flies
HypixelLatest-Boost - LatestHypixel gives you a boost at the start if it's on, For hypixel, this will now autoban you DO NOT USE it there
BoostDelay - how long after you toggle fly until timer is back to normal speed
BoostTimer - How much above 1 speed you wanna go (0.54 = 1.54 timer speed)
Mark - For some fly, has a mark to show you where you can't go
ForceUnicodeChat - Chats in a fancy text when you write stuff
Freeze - You can freeze in the air (AAC bypass)
Fucker - For Bedwars, eggwars, other stuff.
ID - The block ID you wanna fuck
Instant - Will Fucker fuck (break) blocks instantly?
ThroughWalls - Fucks blocks through walls
Swing - Swings when you fuck
Rotations - Aims at the block being fucked
Surroundings - Fucks the block's surroundings before fucking it.
Action - Whether to break the block or right click it when fucking it.
NoHit - Doesn't fuck when you are hitting a target
Ghost - When you die, you'll be able to look around the area you died
GhostHand - You can reach through blocks.
ID - The block you wanna be able to reach
GodMode - Teleports you in place to godmode when you die, bypassed AAC 3.2.1

Thanks to icewormy3 for the killaura stuff.

Q: How do I use Scaffold?
A:

Normal: Probably just basic "look at block to place" thing.
Rewinside: idk makes scaffold weird. Somehow bypasses.
Expand: Doesn't look directly at the block's face, instead looks at the blocks face from behind I think. Also able to place block far away from the player.

MaxDelay: Delay between places.
MinDelay: Same thing.
AutoBlock: Automatically switches to a slot with a block in it, then goes back to the slot you're currently on.
StayAutoBlock: Doesn't go back the the slot you're on.
Sprint: Enable this to enable sprinting.
Search: Searches for the face of a block when on a corner of a block. Good for diagonal scaffold.
Eagle: Sneaks at edge of block.
PlaceableDelay: For the delay, instead of starting the delay when you place a block, it starts it when you reach the edge of a block.
BlocksToEagle: Every X block, you eagle.
ExpandLenght: The amount of blocks forwards you place when you're on the Expand mode.
Rotations: Look at the face of the block when place.
KeepRotations: Look at the face of the block all the time. Disables KillAura.
Zitter: Goes side by side.
Zitter mode:
Teleport: Teleports side by side.
Smooth: Presses the buttons to go side by side.
ZitterSpeed: It augments your speed for some reason.
ZitterStrength: The amount of time before going the other way.
--I could be wrong for the zitter stuff--
Timer: The timer at which the game goes when scaffolding.
SpeedModifier: The speed which you gain when placing a block. 0 to stop when placing a block, 2 to go faster when placing a block.
SameY: If enabled, you can't go upwards with the scaffold.
AirSafe: Makes it so that when in air, you can't fall off.
Counter: Counts the amount of block you have left next to the crosshair. Purely visual.
Mark: Marks where the next block is going to be placed. Purely visual.
Q: How do I use Tower?
A:

Jump: Jumps to go up. Set jump value under "JumpMotion"
Motion: Same thing as jump except it goes up at a constant pace and stops to place a block.
ConstantMotion: Same thing as Motion except just goes up not waiting for the block to be placed.
MotionTP: I guess same thing as motion but you teleport? Honeslty idk.
Packet: Just uses packets to place blocks I guess.
Teleport: Teleports upwards instead using motion. smile
AAC3.3.9: I guess it's motionY0.41

AutoBlock: Automatically switches to a slot with a block in it, then goes back to the slot you're currently on.
StayAutoBlock: Doesn't go back the the slot you're on.
Swing: If enabled, you swing your arm when placed.
StopWhenBlockAbove: Stops when a block is above your head, obviously.
Timer: The timer at which the game goes when towering.
JumpMotion: The motion at which you go when jumping. 0.42 is legit.
JumpDelay: The delay before jumping again.
ConstantMotion: The motion at which you go when using ConstantMotion.
ConstantMotionJumpGround: Probably the motion at which you go when placing a block (?).
TeleportHeight: The height at which you teleport when using Teleport.
TeleportDelay: The delay before teleporting again.
TeleportGround: Goes to the ground when there is no ground right underneath you.
TeleportNoMotion: Gets rid of motion when using Teleport.
Counter: Counts the amount of block you have left next to the crosshair. Purely visual.
Q: How can I obfuscate a script I made?
A: Check this out.

If there are still some questions you have, please discuss them in this thread and I'll try to answer as soon as possible. I might even add it to the FAQ. :axodrugs:

**Comment by NurMarvin** [comment]
The nextgen version of LiquidBounce is planned to have localized module descriptions etc

**Comment by xWhitey** [comment]
I think, you should learn English better.
