### ISSUE TITLE
[FEATURE] Spambot

### ISSUE THREAD

**Issue by Soulplexis** [CCBlueX/LiquidBounce#341]
**Describe your feature request.**
Uses alts or random usernames to join the server you're on. Like OQ-Minebot. they can copy your actions, maybe? is this possible to put into Minecraft client in Nextgen?

**Comment by NurMarvin** [comment]
Out of scope for LiquidBounce. We are a client to cheat and grief, not a spamming service.
Despite that it would also be very inefficient to into the client because you would want to write something like Minecraft bots as low-level as possible to gain the best possible performance which you won't be able to achieve by implementing it directly in the Minecraft client.
