### ISSUE TITLE
[BUG] InventoryCleaner always leaves useless things.

### ISSUE THREAD

**Issue by ShootForever-codejoe** [CCBlueX/LiquidBounce#3529]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.7.2

### Operating System

Windows 11

### Minecraft Version

1.21

### Describe the bug

InventoryCleaner always leaves some useless things such as clothes and swords. These extra things are always low-level. It leads to mess in my inventory.

### Steps to reproduce

Turn on InventoryCleaner and let it start to clean.

### Client Log

```shell
No log.
```

**Comment by superblaubeere27** [comment]
Can you show an example inventory so we can replicate it?

**Comment by 1zun4** [comment]
![image](https://github.com/user-attachments/assets/872296f0-adc9-4720-9ae6-764942a54b57)

One thing I have noticed is, InventoryCleaner keeps all buckets. I think there should be an option that allows you to "Keep Buckets" or not, because in my case I never use them but CubeCraft for example fills your inventory up with hay, eggs, lapis, xp bottles and armbrust which are useless items to me in most cases.

Therefore there should be options such as:
- Keep Buckets
- Keep Enchantables
- Keep Throwables

and maybe a way to throw out unfavorable block types such as hay. We do have a block selector like for Fucker, maybe it could be useful?

Also in this case it kept 3 pieces of armor for no reason and a backup sword - which is not really intentional and probably a bug as well, good as a backup sword, but it should really only do that on low durability... Related to https://github.com/CCBlueX/LiquidBounce/issues/3522

Due to the fact [tenacc](https://github.com/superblaubeere27/tenacc) is missing currently I was not able to store the inventory for debugging purposes.
