### ISSUE TITLE
[FEATURE]Improve Scaffold ExtraClick

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#3726]
### LiquidBounce Branch

Legacy

### Describe your feature request.

this function doesnt care about rightClickDelayTimer, so player will be detected as FastPlace(Hawk)

**Comment by ghost** [comment]
Hawk is not a good anticheat. It doesn’t understand the situation the player is in. There’s no improvement needed since it already follows minecraft logic.

As for the rightClickDelayTimer, it is only used when you are holding the right click, every 6 ticks you place a new block. This can get avoided if you don’t hold the right click button. Makes sense, right?

**Comment by Husky272** [comment]
okay
