### ISSUE TITLE
[BUG]Click Velocity got detected by movement sensetive anticheats

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4410]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

no

### Steps to reproduce

https://www.bilibili.com/video/BV1VTDqYhEUk/

### Client Log

```shell
no
```

**Comment by ghost** [comment]
It is not meant to work on any anti-cheat that really cares about movement checks, as it violates vanilla attack movement slow down  logic.

**Comment by Husky272** [comment]
It works well in AAC5,but can u make an option so that it can work like a legit player

**Comment by EclipsesDev** [comment]
this might be useful if combined with jump velo, but idk

**Comment by ghost** [comment]
> It works well in AAC5,but can u make an option so that it can work like a legit player

I tested it, doesn't work on neither Loyisa nor Anticheat-Test with Grim.

EDIT: Also if I make it "work like a legit player", the whole mode will be rendered useless because of how Minecraft handles sprinting when attacking.

https://github.com/CCBlueX/LiquidBounce/blob/legacy/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/Velocity.kt#L362-L377

**Comment by Husky272** [comment]
To make it legit and useful u should make a range for hurttime rather than send all attack packets in just one tick

**Comment by Husky272** [comment]
https://github.com/RE-KevinClient/KevinClient-Reborn/blob/master/src/minecraft/kevin/module/modules/combat/AntiKnockback.kt
