### ISSUE TITLE
[FEATURE] skeet clickgui design

### ISSUE THREAD

**Issue by Righted1** [CCBlueX/LiquidBounce#476]
**Describe your feature request.**
add a skeet/gamesense clcikgui option to the clickgui-design tab

**Additional context**
when you run out of space on a tab, make it scrollable

**Comment by NurMarvin** [comment]
If this is meant for the legacy version of LiquidBounce, then no, we don't really work on it anymore unless people PR stuff for it.
If this is meant for the nextgen version of LiquidBounce, then still no, because for the nextgen version you can make the UIs yourself, so maybe someone will make a Skeet-like ClickGUI or maybe not, but we won't add it to the base version
