### ISSUE TITLE
[BUG]Scaffold Spoof AutoBlock doesnt work properly

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4805]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

when I use Spoof AutoBlock and switch slot between usable items I find this https://www.bilibili.com/video/BV1AkiXYQEJK/
But if I enable AutoTool bug wont happen.

### Steps to reproduce

no

### Client Log

```shell
no
```

**Comment by ghost** [comment]
You are not meant to switch slots. AutoBlock is meant to stop modifying the slot when the user switches to another slot manually.

The real issue is with AutoTool. It is NOT resetting the modified slot when you are trying to switch to a new slot.

EDIT: To clarify, this:

> AutoBlock is meant to stop modifying the slot when the user switches to another slot manually.

is changeable, meaning you can either make it so it doesn't stop modifying the slot or it stops modifying. I just have set it so SilentHotbar always resets when the user wants to choose a different slot, because the user is prioritized first, and that's how also way older builds' have their logic.

See here: https://github.com/CCBlueX/LiquidBounce/blob/legacy/src/main/java/net/ccbluex/liquidbounce/utils/SilentHotbar.kt#L25-L32

The behavior in other words is modifiable.
