### ISSUE TITLE
[BUG] [IMPORTANT] Banned from hylex with default config

### ISSUE THREAD

**Issue by 11334464** [CCBlueX/LiquidBounce#4814]
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Windows 11

### Minecraft Version

1.21.1

### Describe the bug

i got banned from hylex for 1 day with the normal config
![image](https://github.com/user-attachments/assets/a17157d7-e29e-4e5e-938d-4d95366c8b6b)
![Screenshot 2024-12-06 170222](https://github.com/user-attachments/assets/c75ed91c-dc66-4909-8b9d-0e712dd38137)

### Steps to reproduce

go on hylex bedwars with default config nothing bypasses

### Client Log

```shell
none
```

**Comment by SuicidalEeper** [comment]
Pretty sure they patched most stuff within a week

**Comment by DataM0del** [comment]
So important that you can find another Brazil VPN and join with a different username!!!

**Comment by 1zun4** [comment]
https://github.com/CCBlueX/LiquidCloud/commit/9afb5ccec68193171438c4edcc664c7a90e1f6e2 Config is now removed.

**Comment by 1zun4** [comment]
![image](https://github.com/user-attachments/assets/ab81fd3c-07fd-46b5-8b8c-5bfbc180ccd3)
Hylex bans ViaFabricPlus, ViaFabric, ViaProxy and so on. Report the issue to https://github.com/ViaVersion/ViaFabricPlus/issues - not here.

I also deleted the https://github.com/CCBlueX/LiquidCloud/commit/9afb5ccec68193171438c4edcc664c7a90e1f6e2 config - because without ViaFabricPlus on 1.20.6 it will not work as intended. It would need to be used on 1.21.1 without on-tick exploit to work again.
