### ISSUE TITLE
[BUG]MLG Nofall causes fake water

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4907]
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

latest

### Describe the bug

https://www.bilibili.com/video/BV1r8BwYyEwA/

### Steps to reproduce

1. enable NoFall and fall from a high place
2. before placing water make sure ur client side rotation has aimed at a block
3. fake water

### Client Log

```shell
no
```

**Comment by ghost** [comment]
I cannot reproduce this one. Have you enabled any module that affects rotations? Or anything weird?

EDIT: I might know the cause, however:

https://github.com/CCBlueX/LiquidBounce/blob/legacy/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/item/MixinItem.java#L20-L39

This is the raycast process behind the scenes when you interact with an item. It currently uses the new rotation that the server does not know yet, instead of the last rotation that the server knows. But I doubt that's really the issue since the difference is 1 tick, plus you use instant rotations. If there is any chance that this could possibly fix the issue, then try this build out:

https://easyupload.io/4zjeng

It uses the last known server rotation instead of the new rotation made by the client. But please make sure the official build still causes that issue.

**Comment by Husky272** [comment]
I disable all modules that affects rotation，this bug still happen.The farther the target block from the client's perspective is from the player's landing point, the higher the success rate. and if u still cant reproduce it, try to jump(or anything that can boost ur horizontal speed) before u jump off.

**Comment by ghost** [comment]
Do you maybe use other mods that could possibly mess with the rotations/raycast? Could you tell me if you use any mods?

**Comment by Husky272** [comment]
I just use InputFix and LB

**Comment by Husky272** [comment]
[Test.txt](https://github.com/user-attachments/files/18143824/Test.txt)

**Comment by ghost** [comment]
Did the build work?

**Comment by Husky272** [comment]
yes

**Comment by ghost** [comment]
Wait, so this fixed it for you?

**Comment by Husky272** [comment]
> I cannot reproduce this one. Have you enabled any module that affects rotations? Or anything weird?
> 
> EDIT: I might know the cause, however:
> 
> https://github.com/CCBlueX/LiquidBounce/blob/legacy/src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/item/MixinItem.java#L20-L39
> 
> This is the raycast process behind the scenes when you interact with an item. It currently uses the new rotation that the server does not know yet, instead of the last rotation that the server knows. But I doubt that's really the issue since the difference is 1 tick, plus you use instant rotations. If there is any chance that this could possibly fix the issue, then try this build out:
> 
> https://easyupload.io/4zjeng
> 
> It uses the last known server rotation instead of the new rotation made by the client. But please make sure the official build still causes that issue.

I use this version then bug fixed

**Comment by ghost** [comment]
Interesting...

**Comment by ghost** [comment]
I cannot reproduce that issue at all btw.

**Comment by ghost** [comment]
Anyway, replaced it with the build's code. Enjoy
