### ISSUE TITLE
[BUG] sprint issues

### ISSUE THREAD

**Issue by SpoilerRules** [CCBlueX/LiquidBounce#610]
### LiquidBounce Build/Version

Nextgen: 220596c

### Operating System

Windows 10

### Minecraft Version

1.17.1

### Describe the bug

when i toggle off scaffold and minecraft's default toggle sprint is enabled, i can't sprint forcely for like 1 seconds. when i use jump & optimizeforcooldown options on criticals, sometimes criticals is forcing me to sprint multidir/alldirections.

edit: scaffold also forcing me to sprint multidir/alldirections

### Steps to reproduce

explained in describe the bug selection

### Client Log

```shell
this isn't needed i guess
```

**Comment by ghost** [comment]
> when i toggle off scaffold and minecraft's default toggle sprint is enabled, i can't sprint forcely for like 1 seconds.

It's not a bug, it's a feature, because of this code that exists in the Scaffold module:

`RotationManager.aimAt(target.rotation, ticks = 30, configurable = rotationsConfigurable)`

If it is disabled/there is no other block it can place, it will take 30 ticks to "turn off", and 30 ticks = 1.5 seconds.

Basically, none of these are bugs, they are intentional. The rotation system that LiquidBounce NextGen uses simulates realistic movements, which means it makes you strafe around the opponent when you look at the enemy, unlike going in a straight direction. It doesn't allow you to sprint on wherever direction you want apart from: Forwards, Forwards+Left and Forwards+Right. It's like you are in first person mode and cannot sprint backwards or sideways.

**Comment by ghost** [comment]
This issue can be closed.
