### ISSUE TITLE
[BUG] Check Sodium combability with Xray

### ISSUE THREAD

**Issue by 1zun4secondary** [CCBlueX/LiquidBounce#686]
### LiquidBounce Build/Version

nextgen

### Operating System

Windows 11

### Minecraft Version

1.18.1

### Describe the bug

Xray has been added from https://github.com/CCBlueX/LiquidBounce/pull/684 pull request but still has to be verified to work with Sodium.

### Steps to reproduce

none

### Client Log

```shell
none
```

**Comment by ghost** [comment]
So, I tested it by downloading and extracting the sodium jar file to the mods folder instead of making build.gradle work with it because it wouldn't work at all for some reason. Last tested version: `mc1.18.1-0.4.0-alpha6`

The module didn't really do its purpose, except for the FullBright option. I'm not really sure if this is a correct way to test it though.

Some screenshots for proof:

![Base Profile Screenshot 2022 01 18 - 17 25 44 43](https://user-images.githubusercontent.com/70612656/149966652-47b97eb2-d9e5-43e7-bfd6-ec6d56babd54.png)
![Base Profile Screenshot 2022 01 18 - 17 25 58 19](https://user-images.githubusercontent.com/70612656/149966661-e5520acc-f427-4f30-9c09-7e644420dd5b.png)

Mod used: `sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14`
