### ISSUE TITLE
A dumb question

### ISSUE THREAD

**Issue by OrdinaryHacker** [CCBlueX/LiquidBounce#743]
### Describe your feature request.

Hello, Im newcomer, I would like to ask how to download in Actions if it is even possible.

**Comment by derech1e** [comment]
You can download all artifacts here: https://liquidbounce.net/download

**Comment by OrdinaryHacker** [comment]
Yes, but latest legacy build is from march 10

**Comment by derech1e** [comment]
![image](https://user-images.githubusercontent.com/39240736/160282312-a625cb06-c152-483a-8b56-0d1cab1637ed.png)

**Comment by OrdinaryHacker** [comment]
![Untitled](https://user-images.githubusercontent.com/92876095/160283542-55f58bfd-1dd8-4fde-ab9e-6b5c76920664.png)
But latest is from yesterday

**Comment by ghost** [comment]
He probably wants the pending pull request's version of LiquidBounce Legacy.

**Comment by OrdinaryHacker** [comment]
![image](https://user-images.githubusercontent.com/92876095/160284815-66cfbb16-cbbe-40eb-9b60-22e1dfa5aa35.png)
This

**Comment by bestnub** [comment]
What you are looking for are unaccepted requests. You can fork the projekt yourself, merge the branches from mems in your own and build a jar. The website only shows merged updates because github only looks for changes in branch lecgacy and nextgen as you can see [here](https://github.com/CCBlueX/LiquidBounce/blob/nextgen/.github/workflows/build.yml).

**Comment by OrdinaryHacker** [comment]
oh ok, ty.
