### ISSUE TITLE
[BUG] ScanExtraRange makes KillAura not hit + possible Solution

### ISSUE THREAD

**Issue by bestnub** [CCBlueX/LiquidBounce#759]
### LiquidBounce Build/Version

nextgen

### Operating System

Windows 10

### Minecraft Version

1.18.2

### Describe the bug

If you are just enougth in range of your target for killaura to hit and ScanExtraRange is set to anything but 0 it will most of the time not hit and just look up and down. Only if the rotation is actually in range it will hit. If you turn ScanExtraRange to 0 it will only choose rotations it actually can hit.

I might found the problem causing this behavior:

In EntityExtensions.kt in fun getNearestPoint() it supposedly returns the nearest point. But it only returns the edges and not points on the sides of the hitbox, which might be closer to the eye  point of the player. This causes the client to think the target is farther away than it actually is and doesn't aim at a point wich it can actually hit. To fix it, a correct implementation of fun getNearestPoint() is needed.

### Steps to reproduce

Set KillAura range to 3
Go to target about 2.95 or as close to 3 blocks away (with tp command or clip 0.01)
Set ScanExtraRange to 3 and to 0 and see the result

### Client Log

```shell
null
```

### Screenshots

![image](https://user-images.githubusercontent.com/63472070/164944557-bfab0710-a714-4a4b-b9b7-ed3c486d2587.png)

**Comment by ghost** [comment]
It has nothing to do with the function shown above. Fixed in these commits of this pending PR: https://github.com/CCBlueX/LiquidBounce/pull/819/commits/32ade6b2ecb0d8208cc4a0c6913a4f3caa3a5225, https://github.com/CCBlueX/LiquidBounce/pull/819/commits/8479930af1fdc9dfdf118251c424510d5e1d8525

The issue had to do with the `maxDistanceSquared` variable considering the distance of the farthest-distance-sorted entity.

**Comment by ghost** [comment]
This issue can now be closed.
