### ISSUE TITLE
[BUG] Impossible to add more than 1 Microsoft Account into Account Manager

### ISSUE THREAD

**Issue by kaduvert** [CCBlueX/LiquidBounce#769]
### LiquidBounce Build/Version

LiquidBounce 1.8.9 b73 release

### Operating System

Linux

### Minecraft Version

1.8.9

### Describe the bug

When trying to add more than one account into the Alt Manager by clicking on "Login with Microsoft" it always displays the old account in the browser with no way to choose another one

Clicking on Cancel redirects to localhost, saying: No code in query
clicking on Continue says: Account already added

### Steps to reproduce

- Go to Account Manager
- Add Microsoft Account
- Try to add 2 different Microsoft Accounts

### Client Log

```shell
no (relevant) log output
```

### Screenshots

![Bildschirmfoto von 2022-05-09 10-06-52](https://user-images.githubusercontent.com/70949550/167367918-609476fd-4360-444c-9503-537c1642cced.png)

**Comment by 1zun4secondary** [comment]
Yes. This is problematic because if you sign into Microsoft Account, you will always be logged into this account and every time you try to login again, it will go straight into logging in the old account. I am not sure how to address this issue, because Microsoft does not offer any good way to prevent this, besides us opening a cleared content browser.

**Comment by 1zun4secondary** [comment]
Ok. There is a parameter from microsoft which allows you to force the user to select account instead of automatically signing in:
`prompt=select_account`

**Comment by 1zun4secondary** [comment]
fixed by https://github.com/CCBlueX/LiquidBounce/commit/baffbcc2ebd5a13c6e4fa138552a3e3bc75c6021
