### ISSUE TITLE
Downloading terrain... glitched

### ISSUE THREAD

**Issue by Templom162** [CCBlueX/LiquidBounce#793]
### LiquidBounce Build/Version

b73

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

I was oppening my world and Downloading Terrain... glitched.
Can you fix it in b74?

### Steps to reproduce

Step 1: Join into a server/world.
Step 2: Check it.

### Client Log

```shell
None
```

### Screenshots

![Képernyőkép 2022-06-14 162042](https://user-images.githubusercontent.com/107716554/174837368-5f2cc922-2e22-40b1-b50f-a1f2b8b71cee.png)

**Comment by Templom162** [comment]
Please fix this on b74!

**Comment by 1zun4secondary** [comment]
That is not really a glitch, but due to the fact that minecraft sometimes gets stuck in "Downloading terrain". The background is tranclucent in these cases, which allows you to see the game world already before it was even loaded up, but that is no issue. If you are stuck in this screen, try cancel and reconnecting. Nothing that we could fix.
