### ISSUE TITLE
[BUG] Button position confilct with ViaForge

### ISSUE THREAD

**Issue by HowardZHY** [CCBlueX/LiquidBounce#896]
### LiquidBounce Build/Version

b74

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

the antiforge button was replaced by viaforge button
![image](https://user-images.githubusercontent.com/96782166/216837060-53f9afe5-73f1-4473-808f-3c5d36a5e77b.png)

### Steps to reproduce

install latest viaforge from curse
and see

### Client Log

```shell
/
```

### Screenshots

![image](https://user-images.githubusercontent.com/96782166/216837075-70ea1672-e8e5-4941-96c5-36869bbc650d.png)

**Comment by 1zun4secondary** [comment]
Yes, I know about this, but what are you expecting from us?

**Comment by HowardZHY** [comment]
move button to somewhere else

**Comment by 1zun4secondary** [comment]
Legacy is not going to receive any changes from me, so unlikely that this is going to change anytime soon.

**Comment by HowardZHY** [comment]
hope someone else can see this and fix

**Comment by 1zun4secondary** [comment]
So I decided to add ViaForge as supported mod to the LiquidLauncher, because both projects share the same license and are open-source.

![image](https://user-images.githubusercontent.com/69533520/217510986-8608488f-dceb-49e8-abf4-08f674c5ab7c.png)

But before I modified the JAR and moved the button from x 5 to 211 and y 6 to 8.
![image](https://user-images.githubusercontent.com/69533520/217511062-7929cf29-cee6-4447-8d5a-9c25566eea0e.png)
I could also have modifed the code from https://github.com/FlorianMichael/ViaForge but that was much quicker.

Sadly there is no offical maven for ViaForge and of course the JAR is modified now anyway, so I uploaded it to our own server:
https://maven.ccbluex.net/net/ccbluex/viaforge/1.8.9-2.0.0-patch1/viaforge-1.8.9-2.0.0-patch1.jar

Now it looks like this:
![image](https://user-images.githubusercontent.com/69533520/217511625-7bff3c3b-349c-42fc-8c9a-b0bb0d5ad087.png)

**Comment by florianreuth** [comment]
I will probably remove the button in ViaForge 3 anyway and add a collapsible list on the right side of the page, then the problem should be solved.

**Comment by CzechHek** [comment]
Why not just move the AntiForge button elsewhere when ViaForge is installed? Certainly better than to make a fork of it and even distribute it.

**Comment by florianreuth** [comment]
yeah you could also go for something like that

**Comment by 1zun4secondary** [comment]
Users on the LiquidLauncher have the properly fixed button position, anything else doesn't matter to me.
The button has been there forever, on every LiquidBounce version that ever existed, just because one mod conflicts with this I am not going to change this.

**Comment by florianreuth** [comment]
I can move the button if LiquidBounce is installed
