### ISSUE TITLE
[FEATURE] Killaura customizable randomcenter and range calculation fix

### ISSUE THREAD

**Issue by OrdinaryHacker** [CCBlueX/LiquidBounce#920]
### Describe your feature request.

Randomcenter is detected on anticheats like matrix which flags you for "shake". You can bypass this by lowering your turnspeed to 20(max) when the crosshair movement is slower but also it take some time to aim on target. I think every forked version of LB has this feature. 
Range calculation is broken since forever. If you are trying to make config for good anticheats you will have to put yourselft in disadvantage because it flags you with legit range. When you set range to 3 your real range is around 2.85 so you need to use range around 3.1-3.15 which flags for some reason. Tested on cracked Buzz.

**Comment by ghost** [comment]
> Randomcenter is detected on anticheats like matrix which flags you for "shake". You can bypass this by lowering your turnspeed to 20(max)

You can bypass this by lowering the difference between the new spot and the old spot.

> When you set range to 3 your real range is around 2.85 so you need to use range around 3.1-3.15 which flags for some reason.

Both LiquidBounce Legacy and Nextgen as of the time of writing use loops to detect possible spots. However, they cannot find the perfect spots to give the user perfect reach results. This is fixed in a pending nextgen version only pull request of mine. Here, take a look:
https://github.com/CCBlueX/LiquidBounce/blob/8479930af1fdc9dfdf118251c424510d5e1d8525/src/main/kotlin/net/ccbluex/liquidbounce/utils/aiming/RotationsUtil.kt#L100

**Comment by 1zun4secondary** [comment]
Similar issue: https://github.com/CCBlueX/LiquidBounce/issues/746

**Comment by ghost** [comment]
Reach calculation is fixed, an option `Micronized` with `MicronizedStrength` as a suboption has been added (long time ago) that takes control of the randomization, therefore this issue is now closed.
