### ISSUE TITLE
[FEATURE] Few possible improvements for Scaffold module.

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#927]
### Describe your feature request.

These are my two ideas on how Scaffold could be improved.

* Instead of just targeting the center of a block, it should target at a point where it should have as less rotation movement as possible, essentially having the same logic as KillAura.

* A CPS option, to simulate struggle. Should occur before and after placing blocks, just like a really good bridger does it.

These improvements should bypass most modern anti-cheats, additionally looking like a bridge-tryhard to the other player's eyes.

### Additional context

This idea is mostly for the nextgen version, but could also apply for legacy, best of both worlds.

**Comment by gabrielvicenteYT** [comment]
+1
Though I used to be retarded (And still am quite a bit), I fully agree with you. There should also be randomcenter for scaffold, since all clicking methods make the mouse move a little bit. Keep in mind that my idea should also be made into a scaffold check for anticheats, since it could help detect some scaffolds. Anticheats should also check for non-realistic shaky aiming, since alot of clients exaggarate their random rotations.
