### ISSUE TITLE
[BUG] ClickGui snaps when out of bounds

### ISSUE THREAD

**Issue by derech1e** [CCBlueX/LiquidBounce#999]
### LiquidBounce Build/Version

b78 git-9ba674b

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

If you scroll the GUI outside of the actual viewport and then change something in the values, the GUI snaps back into the actual viewingport. Furthermore, the windows are rearranged irregularly both vertically and horizontally. This is really annoying as you have to keep rearranging the tabs and not being able to change the values right on after the other.

> I noticed that there is also a strange behavior when switching between different window sizes such as full screen and window. A similar result emerges there but this needs to be further investigated.

### Steps to reproduce

https://user-images.githubusercontent.com/39240736/232593626-3a1fe468-8fd4-4a08-a0e3-f753045befd3.mp4

### Client Log

```shell
Not required.
```

**Comment by CzechHek** [comment]
Intended behaviour, panels were redone not to be movable beyond window border. Their positions are updated when mouse button is held, so that ClickGUI doesn't get reordered every time you open it in a smaller window.

Multiple solutions:
1. Toggleable switch for panel out of bounds checks, ...
2. Fix panel scrolling feature so that it wouldn't scroll beyond window border
3. Using CTRL + Scroll to easily change ClickGUI scale and temporarily make it smaller, ...

I will add 1, 2 to my todo list, 3. is already a thing.

**Comment by derech1e** [comment]
> Intended behaviour, panels were redone not to be movable beyond window border. Their positions are updated when mouse button is held, so that ClickGUI doesn't get reordered every time you open it in a smaller window.
> 
> Multiple solutions:
> 
> 1. Toggleable switch for panel out of bounds checks, ...
> 2. Fix panel scrolling feature so that it wouldn't scroll beyond window border
> 3. Using CTRL + Scroll to easily change ClickGUI scale and temporarily make it smaller, ...
> 
> I will add 1, 2 to my todo list, 3. is already a thing.

I think the panel scrolling feature was intended to scroll out of bounds, so you can reach the values that are out of your viewport. It's the whole point of this feature, isn't it? Therefore your second point doesn't really make sense in my opinion.
The first is the best and only solution for this problem, to coexist with the other stuff.
